language: bash

env:
  - PASS_VERSION=1.7.3
  - PASS_VERSION=master

addons:
  apt:
    packages:
      - shellcheck
      - cabal-install

before_script:
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xvf password-store-$PASS_VERSION.tar.xz
  - ln -s password-store-$PASS_VERSION/src/password-store.sh pass
  - export PATH=$PATH:.
  - rm -rf output
  - mkdir output
  - export PATH=$PATH:./output/bin

before_cache:
  - rm $HOME/.cabal/logs/build.log

cache:
  directories:
    - $HOME/.cabal

script:
  - make lint
  - PREFIX=output BASHCOMPDIR=output make install
  - PREFIX=output BASHCOMPDIR=output make uninstall

notifications:
  email:
    recipients:
      - frode.aa+pass-oauth2@gmail.com
    on_success: never
    on_failure: always
