.TH pass-auth2 1 "2019 July 6" "Password store OAUTH2 extension"

.SH NAME
pass-oauth2 - a \fBpass\fP(1) to exchange refresh token for an access token

.SH SYNOPSIS
.B pass oauth2
[
.I OPTIONS
]... [
.I pass-name
]

.SH DESCRIPTION

.BR pass-oauth2
extends the
.BR pass(1)
utility with the
.B oauth2
command for exchanging refresh token for an access token

.SH COMMANDS
.TP
\fBoauth2\fP [ \fI--clip\fP, \fI-c\fP ] \fIpass-name\fP
.br
Print the access token exchanged from the refresh token stored in
\fIpass-name\fP using \fBcurl\fP(1). If \fI--clip\fP or \fI-c\fP is
specified, do not print the access token but instead copy it to the
 clipboard using \fBxclip\fP(1) and then restore the clipboard after
 45 (or \fIPASSWORD_STORE_CLIP_TIME\fP) seconds.

.SH SEE ALSO
.BR pass (1)
.BR curl (1)
.BR xclip (1)

.SH AUTHOR
.B pass-oauth2
was written by
.MT frode.aa@gmail.com
Frode Aannevik
.ME .

.SH HOME
.I https://github.com/frodeaa/pass-oauth2

.SH REPORTING BUGS
.I https://github.com/frodeaa/pass-oauth2/issues
